# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Alexandria Software
name: Randall Wood DBA Alexandria Software
subtitle: Small things for iOS and macOS
title_separator: |
author: Randall Wood
description: >- # this means to ignore newlines until "baseurl:"
  Small things for iOS and macOS
baseurl: / # the subpath of your site, e.g. /blog
url: https://alexandriasoftware.com # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: alexandriasw
github_username:  rhwood
minimal_mistakes_skin: default
locale: en-US
breadcrumbs: true
show_date: true
search: true
logo: /assets/images/ASlogo1-128s.png

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
      layout: single
# _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/rhwood
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/alexandriasw
    - label: Facebook
      icon: fab fa-fw fa-facebook
      url: http://www.facebook.com/563380909

after_footer_scripts:
  - https://cdn.iubenda.com/iubenda.js

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.21.0
plugins:
  - jekyll-feed
  - jekyll-include-cache

include:
  - _pages

 # Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
